### ISSUE TITLE
Add Binder button to try the tutorials online

### ISSUE THREAD

**Issue by basnijholt** [ioam/holoviews#536]
It's adding one simple file called environment.yml to the base folder:

```yaml
name: holoviews

dependencies:
  - python=3.4
  - holoviews
  - numpy
```

You could then run the tutorials from Binder. I'll create a pull request if you like.
